name: 'Run detekt with reviewdog'
description: '🐶 Run detekt with reviewdog on pull requests to enforce best practices'
author: 'Alexey Egin (DominuS-RU)'

inputs:
  github_token:
    description: 'GITHUB_TOKEN'
    required: true
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    required: false
    default: 'error'
  detekt_config:
    description: 'yml detekt config'
    required: false
    default: 'default-detekt-config.yml'
  detekt_excludes:
    description: 'Globing patterns describing paths to exclude from the analysis.'
    required: false
    default: '**/build/**,**/.idea/**'
  reporter:
    description: |
      Reporter of reviewdog command [github-pr-check,github-pr-review].
      Default is github-pr-check.
    required: false
    default: 'github-pr-check'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.detekt_config }}
    - ${{ inputs.detekt_excludes }}
    - ${{ inputs.github_token }}
    - ${{ inputs.level }}
    - ${{ inputs.reporter }}
branding:
  icon: 'check-square'
  color: 'orange'
